# Generated by Django 5.2.8 on 2025-11-08 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(unique=True, verbose_name='Data e Hora da Consulta')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente de Confirmação'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada'), ('REALIZADA', 'Realizada')], default='PENDENTE', max_length=15)),
                ('data_agendamento', models.DateTimeField(auto_now_add=True)),
                ('medico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'ordering': ['data_hora'],
            },
        ),
    ]
